[project]
name = "squared-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "iazher", email = "imanazher00@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.142.2",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
]

[project.scripts]
squared-api = "squared_api:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
